package org.duckdns.splitvpn

// GENERATED by `./gradlew updateRoutes` — do not edit by hand.
// /24 subnets the cdn services' domains resolved to, as seen from the VDS:
// the phone resolves through the relay, so it sees the same answers.
// Regenerate before a release; the on-device route cache picks up
// moves in between.
object CdnRoutes {
    val BY_SERVICE: Map<String, List<Route>> = mapOf(
        "slack" to listOf(
            Route("3.68.124.0", 24),
            Route("3.68.170.0", 24),
            Route("3.68.175.0", 24),
            Route("3.90.158.0", 24),
            Route("3.91.140.0", 24),
            Route("18.159.197.0", 24),
            Route("18.213.32.0", 24),
            Route("34.195.221.0", 24),
            Route("34.202.253.0", 24),
            Route("44.205.171.0", 24),
            Route("44.216.98.0", 24),
            Route("52.3.167.0", 24),
            Route("52.29.238.0", 24),
            Route("52.200.46.0", 24),
            Route("54.236.104.0", 24),
            Route("108.156.60.0", 24),
        ),
        "twitter" to listOf(
            Route("151.101.204.0", 24),
            Route("162.159.140.0", 24),
            Route("172.66.0.0", 24),
        ),
        "cloudflare" to listOf(
            Route("34.54.86.0", 24),
            Route("34.120.108.0", 24),
            Route("104.18.32.0", 24),
            Route("104.18.33.0", 24),
            Route("104.18.36.0", 24),
            Route("104.18.37.0", 24),
            Route("104.18.41.0", 24),
            Route("150.171.109.0", 24),
            Route("160.79.104.0", 24),
            Route("162.159.128.0", 24),
            Route("162.159.129.0", 24),
            Route("162.159.130.0", 24),
            Route("162.159.133.0", 24),
            Route("162.159.134.0", 24),
            Route("162.159.135.0", 24),
            Route("162.159.136.0", 24),
            Route("162.159.137.0", 24),
            Route("162.159.138.0", 24),
            Route("162.159.140.0", 24),
            Route("172.64.146.0", 24),
            Route("172.64.150.0", 24),
            Route("172.64.151.0", 24),
            Route("172.64.154.0", 24),
            Route("172.64.155.0", 24),
            Route("172.66.0.0", 24),
        ),
    )
}
